---
- name: Play LAB02
  hosts: HQ_RT
  gather_facts: False
  check_mode: True

  tasks:
    - name: Configure Interfaces
      ios_interfaces:
        config: 
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: "{{ item.enabled }}"
      loop: "{{ l3_interfaces }}"

    - name: Configure IP Addresses on L3 Interfaces
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4: "{{ item.ipv4 }}"
      loop: "{{ l3_interfaces }}"
