---
- name: Play LAB01
  hosts: all
  gather_facts: False
  check_mode: True

  tasks:
    - name: DEBUG Inventory Hostname
      debug:
        msg: "Hostname: {{ inventory_hostname }}"

    - name: Get Hostname from Remote Host
      ios_command:
        commands: "show running-config | include hostname"
      register: output

    - name: DEBUG Remote Hostname
      debug:
        msg: "{{ output.stdout[0] | regex_search('(?<=hostname )\\S+')}}"

    - name: Gather Facts
      ios_facts:
        gather_subset: all

    - name: Debug Facts
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: Check and set Hostname and Domain
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"

    - name: Template Sample
      template:
        src: sample_template.j2
        dest: "~/sample_{{ inventory_hostname }}"
      tags: sample