---
- name: Play LAB01
  hosts: all
  gather_facts: False
  check_mode: True

  tasks:
    - name: DEBUG Inventory Hostname and IP
      debug:
        msg: "Hostname: {{ inventory_hostname }} IP: {{ ansible_host }}"

    - name: Get Hostname from Remote Host
      ios_command:
        commands: "show running-config | include hostname"
      register: output

    - name: DEBUG Remote Hostname
      debug:
        msg: "{{ output.stdout[0] }}"

    - name: Check and set Hostname and Domain
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"

    - name: Template Sample
      template:
        src: sample_template.j2
        dest: "~/Develop/ansible_training/sample/{{ inventory_hostname }}"
      tags: sample